import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import FibreSection from "@/components/FibreSection";
import ImageCarouselSection from "@/components/ImageCarouselSection";
import ResponsiveAppBar from "@/components/layouts/ResponsiveAppBar";
import AISPlaySection from "@/components/AISPlaySection";
import SimSection from "@/components/SimSection";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <ResponsiveAppBar/>
                <ImageCarouselSection/>
                <FibreSection/>
                <AISPlaySection/>
                <SimSection/>
            </main>

            <footer className={styles.footer}>
                <div className="copyright-footer">
                    © AISFIBREPHUKET.COM ALL RIGHTS RESERVED.
                </div>
            </footer>
        </div>
    );
}
